-- Consolidated Script for DDL_V2 --

-- SECTION: ADHOC SCRIPTS --
ALTER TABLE dbo.Employees 
ADD PhoneNumber VARCHAR(200000);

CREATE TABLE dbo.Departments (
    DepartmentID INT PRIMARY KEY IDENTITY(1,1),
    DeptName VARCHAR(100) NOT NULL,
    Location VARCHAR(50),
    State Varchar (1000),
    country varchar(255)
);



-- SECTION: GRANTS --
GRANT SELECT ON ALL TABLES IN SCHEMA DBO_WINGSPAN_ANALYTICS TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA DBO_WINGSPAN_ANALYTICS TO ROLE Guest_ANLAYSt;


