GRANT USAGE ON DATABASE WINGSPAN_ANALYTICS TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA DBO_WINGSPAN_ANALYTICS TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DBO_WINGSPAN_ANALYTICS TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA DBO_WINGSPAN_ANALYTICS TO ROLE ANALYST_ROLE;
